version: "3.8"

services:
  app:
    image: app
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 -l
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle
      - jekyll_site:/app/_site
      - jekyll_cache:/app/.jekyll-cache
      - jekyll_sass_cache:/app/.sass-cache
      - jekyll_metadata:/app/.jekyll-metadata

volumes:
  app_bundle:
  jekyll_site:
  jekyll_cache:
  jekyll_sass_cache:
  jekyll_metadata:
